name: "Deploy to FastAPI Cloud"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install FastAPI Cloud CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user "fastapi[standard]" fastapi-cloud-cli
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check FastAPI CLI is available
        run: |
          which fastapi
          fastapi --help

      - name: Deploy to FastAPI Cloud
        run: fastapi deploy
        env:
          FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
          FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
